name: "OpenWrt Feed Bulder"
description: "Build a OpenWrt feed with config"
author: ekkog
runs:
  using: 'composite'
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Check
      shell: bash
      run: feed_build.sh